apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/podinfo
      version: '6.0.0'
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: 1
    ui:
      color: "#d12426"
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.0.0
      # repository: test.rollback/test
      # tag: 6.0.0
