---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/yosephbuitrago/helm
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-charts
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: develop
  secretRef:
    name: helm-charts
  url: ssh://git@github.com/RapidRatings/helm-charts.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/terraform-eks-DemoEnnv
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: stg
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./env/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client